### ISSUE TITLE
Repo is closed but task fails

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Codearte/gradle-nexus-staging-plugin#182] opened 2020-12-10 12:01 UTC
The stacktrace indicates this:

```
500: Server Error, body: [errors:[[id:*, msg:Unhandled: Staging repository is already transitioning: com.example-1234]]]
```

It is probably a Sonatype error, but is there not any way to recheck if their info is correct?

**Comment by szpak** [comment] 2020-12-10 20:03
Please paste more complete log from the execution with `--info` .

**Comment by JavierSegoviaCordoba** [comment] 2020-12-10 20:13
I can't share at this moment because I already published it. Next time I will try. I am using Gradle 6.8 rc1, maybe it can affect?

**Comment by szpak** [comment] 2020-12-10 20:30
It shoudn't matter. Have you called `closeRepository` or `closeAndReleaseRepository`?

**Comment by JavierSegoviaCordoba** [comment] 2020-12-10 20:46
`closeRepository` and I released it manually.

**Comment by szpak** [comment] 2020-12-10 20:58
The task can fail on 5xx error from server, however, I would not expect that particular error. Anyway, please try to release with `--info` next time and we will see if there is anything we can do on the plugin side to prevent/handle that.

**Comment by JavierSegoviaCordoba** [comment] 2020-12-10 23:33
```
All projects evaluated.
:example-core:closeRepository (Thread[Execution worker for ':',5,main]) started.
:example-common:closeRepository (Thread[Execution worker for ':' Thread 4,5,main]) started.
 
> Task :example-core:closeRepository
Caching disabled for task ':example-:closeRepository' because:
  Caching has not been enabled for the task
Task ':example-:closeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Getting staging profile for package group 'com.example'
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
Getting 'open' repository for staging profile '56db21d29080'
Saving repository ID comexample-1132 for reusing in other tasks
Closing repository 'comexample-1132' with staging profile '56db21d29080'
POST request failed. 500: Server Error, body: [errors:[[id:*, msg:Unhandled: Staging repository is already transitioning: comexample-1132]]]
 
> Task :example-core:closeRepository FAILED
:example-core:closeRepository (Thread[Execution worker for ':',5,main]) completed. Took 14.754 secs.
 
> Task :example-common:closeRepository
Caching disabled for task ':example-common:closeRepository' because:
  Caching has not been enabled for the task
Task ':example-common:closeRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
Getting staging profile for package group 'com.example'
DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.
Getting 'open' repository for staging profile '56db21d29080'
Saving repository ID comexample-1132 for reusing in other tasks
Closing repository 'comexample-1132' with staging profile '56db21d29080'
Repository 'comexample-1132' with staging profile '56db21d29080' has been accepted by server to be closed
Getting repository 'comexample-1132'
Requested operation wasn't successful in first try. Retrying maximum 60 times with 5 seconds delay between attempts.
Attempt 1/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Attempt 2/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Attempt 3/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Attempt 4/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Attempt 5/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Attempt 6/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Attempt 7/61 failed. RepositoryInTransitionException was thrown with message 'Repository 'comexample-1132' (in 'open' state) is in transition. Check again later.'. Waiting 5000 ms before next retry.
Getting repository 'comexample-1132'
Requested operation was executed successfully in attempt 8 (maximum allowed 61)
Repository 'comexample-1132' has been effectively closed
:example-common:closeRepository (Thread[Execution worker for ':' Thread 4,5,main]) completed. Took 55.591 secs.
 
FAILURE: Build failed with an exception.
 
* What went wrong:
Execution failed for task ':example-core:closeRepository'.
> 500: Server Error, body: [errors:[[id:*, msg:Unhandled: Staging repository is already transitioning: comexample-1132]]]
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8-rc-1/userguide/command_line_interface.html#sec:command_line_warnings
 
BUILD FAILED in 56s
2 actionable tasks: 2 executed
Watched directory hierarchies: [/Volumes/Dev/repos/multiplatform/example]
javier@Javiers-MacBook-Pro example %

**Comment by szpak** [comment] 2020-12-11 20:17
> DEPRECATION WARNING. The staging repository ID is not provided. The fallback mode may impact release reliability and is deprecated. Please consult the project FAQ how it can be fixed.

Due to that GNSP (most likely) tries to close the repository from another subproject which is has been already requested to be closed. Parallel close/release tasks execution is not supported in that mode. You might want to build everything in parallel and call closeRepository in a regular execution. [*Update. That's not the root cause of the problems - see my next comment*]

However, it would be best to consult FAQ and add [nexus-publish-plugin](https://github.com/marcphilipp/nexus-publish-plugin) which integrates seamlessly with GNSP to make closing/releasing more reliable.

**Comment by JavierSegoviaCordoba** [comment] 2020-12-11 20:24
I will try it, thank you :wink:

**Comment by szpak** [comment] 2020-12-12 01:43
It was a quick comment done in hurry and I completely forgot about one important aspect :).

Don't you also see the following warning in your logs?
> Overriding protection against applying on non-root project. It may cause execution errors if used improperly.

And didn't you add `gnsp.disableApplyOnlyOnRootProjectEnforcement=true` to your project configuration (or Gradle call)?

In general, it doesn't make sense to make more than one close (and one release) task in your whole (multiproject) project. You should implicitly (by just uploading files with `publish*`) or explicitly (with nexus-publish-plugin - recommended) create a staging repository and upload all the artifacts (from all the subprojects) to it (with nexus-publish-plugin it should work also with parallel execution). After that you call the `closeRepository` task on your root project (which should itself `shouldRunAfter` all the publish tasks) to close that staging repository with all the artifacts from all your subprojects (could be used in parallel build with already mentioned `shouldRunAfter`). That's all.

Having multiple closeRepository tasks you try to close the repository multiple time, which has to fail (on the Gradle side). On the Nexus side the repository is closed, because the first close request is effectively completed after some time.

With the following suggestions - nexus-publish-plugin + applying GNSP just in the root project (or in a case of an Android project just one selected subproject) everything should be ok (usually ;-) ).

**Comment by JavierSegoviaCordoba** [comment] 2020-12-12 10:17
I have two projects, but they are published first, then there is only one repo in the nexus web. after that, the close task is called, but the plugin is not being used at root level, it is being used in each subproject, so maybe it is trying to close the same repo two times?  

This is how I configured the CI/CD

```
      - name: Maven publish
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
          gpgKeyName: ${{ secrets.gpgKeyName }}
          gpgPassphrase: ${{ secrets.gpgPassphrase }}
          isReleaseEnv: true
        run: ./gradlew publishAllPublicationsToMavenRepository -Psigning.gnupg.keyName=${{ secrets.gpgKeyName }} -Psigning.gnupg.passphrase=${{ secrets.gpgPassphrase }}
 
      - name: Close Maven repository
        env:
          ossUser: ${{ secrets.ossUser }}
          ossToken: ${{ secrets.ossToken }}
        run: ./gradlew closeRepository
``` 

And yes, I have in my `gradle.properties`
```
gnsp.disableApplyOnlyOnRootProjectEnforcement=true
```

Moving it to the root project should solve the problem then without adding the other plugin?

**Comment by JavierSegoviaCordoba** [comment] 2020-12-12 10:45
Yeah, it solves the problem, really I was doing a stupid thing but I configured it when i had only one project and I forgot this flag. Thank you :)

**Closed as completed** 2020-12-12 10:46 UTC
Labels: waiting for info

**Comment by szpak** [comment] 2020-12-12 14:02
> Moving it to the root project should solve the problem then without adding the other plugin?

The other plugin is recommended to improve the reliability of publishing. For instance, Travis had [problems](https://github.com/travis-ci/travis-ci/issues/9555) with releasing to Maven Central due to varying IP addresses (Nexus binds implicitly created staging repositories to IP). If it works fine with GitHub Actions, you might stay with it. However, currently you have to clean up after any failed releasing - any old open staging repository in Nexus would make another execution failed. With gradle-nexus-plugin you explicitly create the new repository and upload artifacts directly to it. Everything transparently for you - `gradle publish` + `gradle closeRepository` is enough.

**Comment by JavierSegoviaCordoba** [comment] 2020-12-12 15:03
Thank you for all this info, I have a tab in my browser for weeks about that plugin precisely to fix the problems you are mentioning 😂

**Comment by JavierSegoviaCordoba** [comment] 2020-12-13 15:22
@szpak With the NexusPublish plugin now I don't get multiple repositories at the same time and all works like a charm. The only issue I have is I can't get `stagingRepositoryId` working, if I set it to your plugin, the repo created can be `comexample-NNNN` where `NNNN` can be, for example, `1254`, so it can't be closed with the Gradle task. I tried to search about what should be the value of this `stagingRepositoryId` but I found nothing.

If I don't set it, I get the warning but at least MavenPublish doesn't create multiple repositories randomly if it is used via NexusPlugin

**Comment by szpak** [comment] 2020-12-13 20:32
`stagingRepositoryId` should be set automatically by nexus-publish. It is only intended for manual setting with some special use cases. Is there any problem when you use GNSP and nexus-publish and call `publish` and `closeRepository` (e.g. you see the aforementioned warning)?

**Comment by JavierSegoviaCordoba** [comment] 2020-12-13 21:39
The deprecated warning is appearing for me, [here](https://github.com/JavierSegoviaCordoba/NetworkResponse/blob/develop/.github/workflows/master-push.yml) you can see the GitHub workflows to see how I release the projects

**Comment by szpak** [comment] 2020-12-13 21:53
Ok, you are right. To leverage automatic `stagingRepositoryId` passing between plugins `publishToSonatype` and `closeRepository` need to be used in the same Gradle call. However, if it works fine for you with that configuration, you can leave it as is and live with the warning.

**Comment by JavierSegoviaCordoba** [comment] 2020-12-13 22:15
Calling it at the same time with parallel configuration enabled can cause issues?

**Comment by szpak** [comment] 2020-12-13 22:31
It is not a officially supported feature, however, in the e2e tests for my plugin I release to test Nexus using 2 parallel Travis builds and it works. Therefore, you can give it a try. However, it that case you should declare that the `closeRepository` task (and for consistency also `releaseRepository`)  `mustRunAfter()` all the `publish` tasks (all the tasks with `Publish` type - `....mustRunAfter(allprojects.tasks.withType(Publish))`). I don't know how to write it in the Kotlin-based configuration.
