### ISSUE TITLE
is there some local setup for this project(1 test fails, the rest pass)

### ISSUE THREAD

**Issue by deanhiller** [Codearte/gradle-nexus-staging-plugin#31] opened 2016-12-23 16:41 UTC
The web page from gradle is this text

```
Condition not satisfied:

result.standardOutput.contains("Using username 'testUsername' and password from repository 'Test repo'")
|      |              |
|      |              false
|      The client will now receive all logging from the daemon (pid: 21753). The daemon log file: /Users/dhiller/.gradle/daemon/2.13/daemon-21753.out.log
|      Starting 26th build in daemon [uptime: 44 mins 34.198 secs, performance: 98%, memory: 28% of 954.7 MB]
|      Executing build with daemon context: DefaultDaemonContext[uid=5057097a-aa33-49ba-99d3-b744b9c1332a,javaHome=/opt/twitter_mde/package/TwitterJDK/e2fcfaf92295baf2a4c041a9680f7f4bf11ef591d26a41ffd77a81c6296d4cd7/Contents/Home,daemonRegistryDir=/Users/dhiller/.gradle/daemon,pid=21753,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
|      Closing daemon's stdin at end of input.
|      The daemon will no longer process any standard input.
|      Starting Build
|      Settings evaluated using settings file '/Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/settings.gradle'.
|      Projects loaded. Root project using build file '/Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/build.gradle'.
|      Included projects: [root project 'uploadArchives']
|      Evaluating root project 'uploadArchives' using build file '/Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/build.gradle'.
|      Compiling build file '/Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/build.gradle' using BuildScriptTransformer.
|      All projects evaluated.
|      Selected primary task 'getStagingProfile' from project :
|      Tasks to be executed: [task ':getStagingProfile']
|      Using username 'dean.hiller@gmail.com' and password from repository 'Test repo'
|      Creating In-memory cache of /Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/.gradle/2.13/taskArtifacts/fileHashes.bin: MaxSize{400000}
|      Creating In-memory cache of /Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/.gradle/2.13/taskArtifacts/fileSnapshots.bin: MaxSize{10000}
|      Creating In-memory cache of /Library/Workflow/gradle-nexus-staging-plugin/build/test/io.codearte.gradle.nexus.functional.PasswordFunctionalSpec/should-read-password-from-repository-configured-in-uploadArchives/.gradle/2.13/taskArtifacts/taskArtifacts.bin: MaxSize{2000}
|      :getStagingProfile (Thread[Daemon worker Thread 2,5,main]) started.
|      :getStagingProfile
|      Executing task ':getStagingProfile' (up-to-date check took 0.0 secs) due to:
|        Task has not declared any outputs.
|      Getting staging profile for package group 'com.example.upload1'
|      :getStagingProfile FAILED
|      :getStagingProfile (Thread[Daemon worker Thread 2,5,main]) completed. Took 4.514 secs.
|       
|      BUILD FAILED
|       
|      Total time: 4.661 secs
|      Stopped 0 compiler daemon(s).
nebula.test.functional.internal.toolingapi.ToolingExecutionResult@564aa7e8

	at io.codearte.gradle.nexus.functional.PasswordFunctionalSpec.should read password from repository configured in uploadArchives(PasswordFunctionalSpec.groovy:16)
```

Std. out is not interesting and only prints out each running test.  There is no std. err.

**Comment by szpak** [comment] 2016-12-23 23:07
Thanks for the report. The value in your `~/.gradle/gradle.properties` was influencing the test result. Should be fixed in master.

**Closed as completed** 2016-12-23 23:06 UTC
Labels: enhancement, testing

**Comment by szpak** [comment] 2016-12-27 12:57
Btw, the test input was somehow useful. The expectation was:
> standardOutput.contains("Using username 'testUsername' and password from repository 'Test repo'")

the standard output contained:
> Using username 'dean.hiller@' and password from repository 'Test repo'

It suggested me what the problem is.
